export const teamMembers = [
	{
		name: "Prakhyath YB",
		src: "/images/team/prakhyath.jpg",
		title: "Team Lead",
		twitter: null,
		instagram: "https://www.instagram.com/prakhyath_yb980/",
		linkedin: "https://www.linkedin.com/in/prakhyath-bhandary-939458240/",
	},
	{
		name: "Sreevalli TS",
		src: "/images/team/sreevalli.jpg",
		title: "Team Lead",
		twitter: null,
		instagram: "https://www.instagram.com/sreevalli_221b/",
		linkedin:
			"https://www.linkedin.com/in/sreevalli-seetha-ramu-9b0560229/",
	},
	{
		name: "Gautam M",
		src: "/images/team/gautam.jpg",
		title: "Design Head",
		twitter: null,
		instagram: "https://www.instagram.com/gautam_m16/",
		linkedin: "https://www.linkedin.com/in/gautam-m-8a4a27225/",
	},
	{
		name: "Nikhil Bharadwaj",
		src: "/images/team/nikhil.jpg",
		title: "Aerodynamics and Finance Head",
		twitter: null,
		instagram: "https://www.instagram.com/_nikkhil03_/",
		linkedin: "https://www.linkedin.com/in/nikhil-bharadwaj-01a611223/",
	},
	{
		name: "Chyawan C",
		src: "/images/team/chyawan.jpg",
		title: "Avionics Head",
		twitter: null,
		instagram: "https://www.instagram.com/chyawan_c/",
		linkedin:
			"https://www.linkedin.com/in/chyawan-chandrashekar-709469261/",
	},
	{
		name: "Adithya DR",
		src: "/images/team/adithya.jpg",
		title: "Flight Test Head",
		twitter: null,
		instagram: "https://www.instagram.com/_adigowda_/",
		linkedin: "https://www.linkedin.com/in/adithya-d-r-979119240/",
	},
	{
		name: "Siddharth Varshney",
		src: "/images/team/siddharth.JPG",
		title: "Web Development Head",
		twitter: null,
		instagram: "https://instagram.com",
		linkedin: "https://www.linkedin.com/in/siddharth-varshney-385a42244/",
	},
	{
		name: "Ashrith P Jain",
		src: "/images/team/ashrith.jpeg",
		title: "Sponsorship Head",
		twitter: null,
		instagram: null,
		linkedin: "https://www.linkedin.com/in/ashrithjain/",
	},
	{
		name: "Lakshmi Manasa",
		src: "/images/team/unknown.jpg",
		title: "Marketing Head",
		twitter: null,
		instagram: "https://www.instagram.com/lakshmimansa_cn/",
		linkedin: null,
	},
	{
		name: "Solomon Dcosta",
		src: "/images/team/unknown.jpg",
		title: "Inventory and Procurement Head",
		twitter: null,
		instagram: null,
		linkedin: null,
	},
];