export const teamMembers = [
	{
		name: "Prakhyath YB",
		src: "./images/pexels-andrea-piacquadio-845434.jpg",
		title: "Team Lead",
		twitter: "https://twitter.com/login",
		instagram: "https://www.instagram.com/prakhyath_yb980/",
		linkedin: "https://www.linkedin.com/in/prakhyath-bhandary-939458240/",
	},
	{
		name: "Sreevalli TS",
		src: "./images/pexels-vinicius-wiesehofer-1130624.jpg",
		title: "Team Lead",
		twitter: "https://twitter.com/login",
		instagram: "https://www.instagram.com/sreevalli_221b/",
		linkedin:
			"https://www.linkedin.com/in/sreevalli-seetha-ramu-9b0560229/",
	},
	{
		name: "Gautam M",
		src: "./images/pexels-hussein-altameemi-2776353.jpg",
		title: "Design Head",
		twitter: "https://twitter.com/login",
		instagram: "https://www.instagram.com/",
		linkedin: "https://www.linkedin.com/in/gautam-m-8a4a27225/",
	},
	{
		name: "Nikhil Bharadwaj",
		src: "./images/pexels-andrea-piacquadio-745136.jpg",
		title: "Aerodynamics and Finance Head",
		twitter: "https://twitter.com/login",
		instagram: "https://www.instagram.com/",
		linkedin: "https://www.linkedin.com/in/nikhil-bharadwaj-01a611223/",
	},
	{
		name: "Chyawan C",
		src: "./images/pexels-andrea-piacquadio-745136.jpg",
		title: "Avionics Head",
		twitter: "https://twitter.com/login",
		instagram: "https://www.instagram.com/",
		linkedin:
			"https://www.linkedin.com/in/chyawan-chandrashekar-709469261/",
	},
	{
		name: "Adithya DR",
		src: "./images/pexels-andrea-piacquadio-745136.jpg",
		title: "Flight Test Head",
		twitter: "https://twitter.com/login",
		instagram: "https://www.instagram.com/",
		linkedin: "https://www.linkedin.com/in/adithya-d-r-979119240/",
	},
	{
		name: "Siddharth Varshney",
		src: "./images/pexels-andrea-piacquadio-745136.jpg",
		title: "Web Development Head",
		twitter: "https://twitter.com/login",
		instagram: "https://instagram.com",
		linkedin: "https://www.linkedin.com/in/siddharth-varshney-385a42244/",
	},
	{
		name: "Ashrith P Jain",
		src: "./images/pexels-andrea-piacquadio-745136.jpg",
		title: "Sponsorship Head",
		twitter: "https://twitter.com/login",
		instagram: "https://www.instagram.com/",
		linkedin: "https://www.linkedin.com/in/ashrithjain/",
	},
	{
		name: "Lakshmi Manasa",
		src: "./images/pexels-andrea-piacquadio-745136.jpg",
		title: "Marketing Head",
		twitter: "https://twitter.com/login",
		instagram: "https://www.instagram.com/",
		linkedin: "https://www.linkedin.com/",
	},
	{
		name: "Solomon Dcosta",
		src: "./images/pexels-andrea-piacquadio-745136.jpg",
		title: "Inventory and Procurement Head",
		twitter: "https://twitter.com/login",
		instagram: "https://www.instagram.com/",
		linkedin: "https://www.linkedin.com/",
	},
];